spring.application.name=chat

server.port=7002

eureka.client.service-url.defaultZone=http://eureka-admin:${EUREKA_PASSWORD}@eureka-server-grpc-server:8761/eureka

management.endpoints.web.exposure.exclude=health,info
management.endpoint.health.show-details=when-authorized
management.endpoint.health.probes.enabled=true