networks:
  private-net:
    driver: bridge
  public-net:
    driver: bridge

services:

  eureka-server-grpc-server:
    container_name: eureka-server-grpc-server-minimum
    networks:
      - private-net
    build: ./eureka-server


  api-gateway:
    container_name: api-gateway-minimum
    networks:
      - private-net
      - public-net
    build: ./api-gateway
    ports:
      - "7000:7000"
    depends_on:
      - eureka-server-grpc-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server-grpc-server:8761/eureka

  session-stateful-server:
    container_name: session-stateful-server-minimum
    networks:
      - private-net
    build: ./cookies-auth
    expose:
      - "7001"
    depends_on:
      - eureka-server-grpc-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server-grpc-server:8761/eureka

  web-socket-chat:
    container_name: web-socket-chat-minimum
    networks:
      - private-net
      - public-net
    build: ./chat
    ports:
      - "7002:7002"
    depends_on:
      - eureka-server-grpc-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server-grpc-server:8761/eureka

  elastic-search-server:
    container_name: elastic-server
    networks:
      - private-net
    build: ./elastic-search
    expose:
      - "7003"
    depends_on:
      - eureka-server-grpc-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server-grpc-server:8761/eureka

  redis-rl:
    image: redis:alpine
    container_name: redis-rate-limiter-minimum
    networks:
      - private-net
    volumes:
      - redis-rl:/data

  redis-l2:
    image: redis:alpine
    container_name: redis-cache-l2-minimum
    networks:
      - private-net
    volumes:
      - redis-cache-l2:/data

  postgres:
    image: postgres:16-alpine
    container_name: postgres-sessions-minimum
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - private-net
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres-sessions:/var/lib/postgresql/data 

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elastic-search-minimum
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - private-net
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana-minimum
    networks:
      - private-net
      - public-net
    ports:
      - "5601:5601"
    depends_on:
      - elastic-search
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200    

  mariadb:
    image: mariadb
    container_name: mysql-images-metadata-minimum
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - private-net
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  es_data:
  redis-rl:
  redis-cache-l2:
  postgres-sessions:
  mysql-data: