server:
  port: 7000

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: redis-rate-limiter
      port: 6379

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: cookies-auth
              uri: lb://COOKIES-AUTH
              predicates:
                - Path=/auth/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 3
                    redis-rate-limiter.burstCapacity: 8
                    key-resolver: "#{@userAddressResolver}"
            - id: chat
              uri: lb://CHAT
              predicates:
                - Path=/chat/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-admin:${EUREKA_PASSWORD}@eureka-server-grpc-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true


  metrics:
    tags:
      application: ${spring.application.name}

    distribution:
      percentiles-histogram:
        "http.server.requests": true

      percentiles:
        "http.server.requests":
          - 0.99
          - 0.95
          - 0.5