server:
  port: 7001

spring:
  application:
    name: cookies-auth
  
  datasource:
    url: jdbc:postgresql://postgres-sessions:5432/postgres-sessions
    username: admin
    password: s3cur3p4SSw0rd
    driver-class-name: org.postgresql.Driver
  
  data:
    redis:
      host: redis-cache-l2
      port: 6379
  session:
    store-type: redis
  
  jpa:
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: http://eureka-admin:${EUREKA_PASSWORD}@eureka-server-grpc-server:8761/eureka

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized